# Generated by Django 5.2.17 on 2026-09-22 09:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('user_registration', 'User Account Registration'), ('provider_verification', 'Provider Credential Verified'), ('provider_revocation', 'Provider Credential Suspended'), ('record_upload', 'Encrypted Record Upload & IPFS Commit'), ('record_blockchain_anchor', 'Record Metadata Anchored on Algorand'), ('access_requested', 'Clinical Access Requested'), ('consent_granted', 'Patient Scoped Consent Granted'), ('consent_revoked', 'Patient Consent Revoked On-Chain'), ('record_retrieval_success', 'Authorized Clinical Decryption & View'), ('record_retrieval_denied', 'Access Denied / Unauthorised Attempt'), ('integrity_check_failure', 'Integrity Alert: Digest or Tag Mismatch'), ('system_operational', 'System Service / Maintenance Event')], max_length=40)),
                ('actor_role', models.CharField(default='system', max_length=20)),
                ('actor_address', models.CharField(blank=True, help_text='Algorand public address', max_length=58, null=True)),
                ('description', models.TextField()),
                ('is_on_chain', models.BooleanField(default=False, help_text='True if anchored on Algorand blockchain ledger')),
                ('algorand_tx_id', models.CharField(blank=True, help_text='Transaction reference on Algorand', max_length=64, null=True)),
                ('confirmation_round', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
