# Generated by Django 5.2.17 on 2026-09-22 09:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinical_purpose', models.TextField(help_text='Detailed justification for clinical access request')),
                ('requested_duration_days', models.PositiveIntegerField(default=7, help_text='Requested access duration in days')),
                ('status', models.CharField(choices=[('pending', 'Pending Patient Review'), ('approved', 'Approved & Granted'), ('rejected', 'Rejected by Patient'), ('expired', 'Request Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.patientprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_requests', to='accounts.providerprofile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentPermission',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='Exact expiry timestamp when permission terminates')),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('algorand_grant_tx_id', models.CharField(blank=True, help_text='Algorand transaction ID for consent grant', max_length=64, null=True)),
                ('algorand_grant_round', models.PositiveBigIntegerField(blank=True, null=True)),
                ('algorand_revoke_tx_id', models.CharField(blank=True, help_text='Algorand transaction ID for revocation', max_length=64, null=True)),
                ('algorand_revoke_round', models.PositiveBigIntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to='accounts.patientprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_permissions', to='accounts.providerprofile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='records.medicalrecord')),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission', to='consent.accessrequest')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
    ]
