# Generated by Django 5.2.17 on 2026-09-22 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('clinical_summary', 'Clinical Summary & Examination'), ('laboratory', 'Laboratory & Pathology Report'), ('radiology', 'Radiology & Medical Imaging'), ('prescription', 'Prescription & Pharmacy Order'), ('discharge', 'Inpatient Discharge Summary'), ('vaccination', 'Immunisation & Vaccination Record')], default='clinical_summary', max_length=30)),
                ('record_date', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('clinical_notes', models.TextField(help_text='Structured clinical notes (encrypted before IPFS commit)')),
                ('diagnosis_code', models.CharField(blank=True, help_text='Opaque ICD/Category code', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_records', to='accounts.providerprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.patientprofile')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_versions', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipfs_cid', models.CharField(help_text='InterPlanetary File System Content Identifier', max_length=100)),
                ('package_digest', models.CharField(help_text='SHA-256 digest computed over complete stored package', max_length=64)),
                ('nonce', models.CharField(help_text='Hex-encoded 96-bit AES-GCM nonce', max_length=64)),
                ('auth_tag', models.CharField(help_text='Hex-encoded 128-bit AES-GCM authentication tag', max_length=64)),
                ('wrapped_key', models.TextField(help_text='Data encryption key wrapped under Key-Encryption-Key')),
                ('file_format', models.CharField(default='application/pdf', max_length=50)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('encrypted_file', models.FileField(blank=True, null=True, upload_to='encrypted_packages/')),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_package', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RecordBlockchainState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorand_tx_id', models.CharField(blank=True, help_text='Algorand Transaction ID', max_length=64, null=True)),
                ('confirmation_round', models.PositiveBigIntegerField(blank=True, help_text='Block round', null=True)),
                ('app_id', models.PositiveBigIntegerField(blank=True, help_text='Algorand App ID', null=True)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('submitted', 'Submitted to Mempool'), ('confirmed', 'Confirmed on Algorand Ledger'), ('rejected', 'Rejected / Error')], default='prepared', max_length=20)),
                ('raw_payload_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_state', to='records.medicalrecord')),
            ],
        ),
    ]
