# Generated by Django 5.2.17 on 2026-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedpackage',
            name='original_filename',
            field=models.CharField(default='clinical_record.txt', max_length=255),
        ),
    ]
