# Generated by Django 5.2.17 on 2026-09-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_encryptedpackage_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedpackage',
            name='ciphertext_b64',
            field=models.TextField(blank=True, help_text='Base64-encoded package bytes for resilient cloud storage', null=True),
        ),
    ]
